tacom/contest/urls.py
from django.urls import path
from django.views.generic import DetailView

from . import views
from .models import Style

app_name = "contest"

urlpatterns = [
    path("", views.PublishedContestListView.as_view(), name="contest_list"),
    path(
        "details/<str:slug>/", views.ContestDetailView.as_view(), name="contest_detail"
    ),
    path(
        "details/<str:slug>/rules/",
        views.ContestRulesView.as_view(),
        name="contest_rules",
    ),
    path(
        "details/<str:slug>/addr/",
        views.ContestDeliveryAddressView.as_view(),
        name="contest_address",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/edit/", views.ProfileEditView.as_view(), name="profile_edit"),
    path("style/<str:slug>/", DetailView.as_view(model=Style), name="style_detail"),
    path("entry/add/", views.AddEntryContestListView.as_view(), name="add_entry"),
    path(
        "entry/add/contest/<str:slug>/",
        views.AddEntryStyleListView.as_view(),
        name="add_entry_contest",
    ),
    path(
        "entry/contest/<str:slug>/",
        views.UsersEntryListView.as_view(),
        name="user_entry_list",
    ),
    path(
        "entry/add/category/<uuid:pk>/",
        views.AddEntryView.as_view(),
        name="add_entry_category",
    ),
    path("entry/edit/<uuid:pk>/", views.EditEntryView.as_view(), name="entry_edit"),
    path(
        "entry/delete/<uuid:pk>/", views.DeleteEntryView.as_view(), name="entry_delete"
    ),
    path(
        "entry/results/<uuid:pk>/",
        views.MyScoreSheetView.as_view(),
        name="entry_results",
    ),
    path(
        "<str:slug>/payment/",
        views.AddPackageForPayment.as_view(),
        name="payment_start",
    ),
    path(
        "<str:slug>/payment/<uuid:package_id>/",
        views.SelectPaymentMethodView.as_view(),
        name="payment_method_selection",
    ),
    path(
        "payment/<uuid:payment_id>/fake/",
        views.FakePaymentView.as_view(),
        name="payment_fake",
    ),
    path(
        "payment/<uuid:payment_id>/transfer/",
        views.TransferPaymentView.as_view(),
        name="payment_transfer",
    ),
    path(
        "payment/<uuid:payment_id>/payu/",
        views.PayUPaymentView.as_view(),
        name="payment_payu",
    ),
    path(
        "payment/payu/<str:contest_slug>/",
        views.PayUPaymentRedirectView.as_view(),
        name="payment_payu_redirect",
    ),
    path(
        "payment/payu/notification/<uuid:payment_id>/",
        views.PayUNotificationView.as_view(),
        name="payment_payu_notification",
    ),
    path(
        "payment/<uuid:payment_id>/paypal/",
        views.PayPalDispatchView.as_view(),
        name="payment_paypal",
    ),
    path(
        "payment/paypal/success/<uuid:payment_id>/",
        views.PayPalSuccessRedirectView.as_view(),
        name="payment_paypal_success",
    ),
    path(
        "payment/paypal/failure/<uuid:payment_id>/",
        views.PayPalFailureRedirectView.as_view(),
        name="payment_paypal_failure",
    ),
    path(
        "<str:slug>/print/", views.AddPackageForPrinting.as_view(), name="labels_start"
    ),
    path(
        "print/<uuid:package_id>/",
        views.LabelPrintoutView.as_view(),
        name="labels_print",
    ),
    path(
        "<str:slug>/mgmt/delivery/",
        views.AddPackageOfDelivered.as_view(),
        name="delivery_select",
    ),
    path(
        "mgmt/delivery/<uuid:pk>/",
        views.ProcessPackageDelivered.as_view(),
        name="delivery_process",
    ),
    path(
        "<str:slug>/mgmt/payments/",
        views.PaymentManagementView.as_view(),
        name="payment_list",
    ),
    path(
        "mgmt/payments/<uuid:pk>/",
        views.PaymentReceivedView.as_view(),
        name="payment_process",
    ),
    path("<str:slug>/judging/", views.JudgingListView.as_view(), name="judging_list"),
    path(
        "<str:slug>/judging-finals/",
        views.JudgingFinalsListView.as_view(),
        name="judging_finals_list",
    ),
    path(
        "<str:slug>/judging-bos/",
        views.JudgeBosView.as_view(),
        name="judging_bos_view",
    ),
    path(
        "<slug:slug>/judging-bos/edit/",
        views.JudgeBosSelect.as_view(),
        name="judging_bos_select",
    ),
    path(
        "<str:slug>/judging-finals/<uuid:category_id>",
        views.JudgingFinalsCategoryView.as_view(),
        name="judging_finals_category",
    ),
    path(
        "scoresheet/<uuid:pk>/", views.ScoreSheetView.as_view(), name="scoresheet_view"
    ),
    path(
        "scoresheet/<uuid:pk>/edit/",
        views.ScoreSheetEdit.as_view(),
        name="scoresheet_edit",
    ),
    path(
        "entry/<uuid:entry>/scoresheet/",
        views.ScoreSheetCreate.as_view(),
        name="scoresheet_create",
    ),
    path(
        "<str:contest_slug>/results/",
        views.MedalsListView.as_view(),
        name="contest_results",
    ),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    path("partners/", views.PartnersGalleryView.as_view(), name="partners_gallery"),
]

tacom/contest/urls/urls.py
from contest import views
from contest.models import Style
from django.urls import path
from django.views.generic import DetailView

urlpatterns = [
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/edit/", views.ProfileEditView.as_view(), name="profile_edit"),
    path("style/<str:slug>/", DetailView.as_view(model=Style), name="style_detail"),
    path("entry/add/", views.AddEntryContestListView.as_view(), name="add_entry"),
    path(
        "entry/add/contest/<str:slug>/",
        views.AddEntryStyleListView.as_view(),
        name="add_entry_contest",
    ),
    path(
        "entry/contest/<str:slug>/",
        views.UsersEntryListView.as_view(),
        name="user_entry_list",
    ),
    path(
        "entry/add/category/<uuid:pk>/",
        views.AddEntryView.as_view(),
        name="add_entry_category",
    ),
    path("entry/edit/<uuid:pk>/", views.EditEntryView.as_view(), name="entry_edit"),
    path(
        "entry/delete/<uuid:pk>/", views.DeleteEntryView.as_view(), name="entry_delete"
    ),
    path(
        "entry/results/<uuid:pk>/",
        views.MyScoreSheetView.as_view(),
        name="entry_results",
    ),
    path(
        "<str:slug>/payment/",
        views.AddPackageForPayment.as_view(),
        name="payment_start",
    ),
    path(
        "<str:slug>/payment/<uuid:package_id>/",
        views.SelectPaymentMethodView.as_view(),
        name="payment_method_selection",
    ),
    path(
        "payment/<uuid:payment_id>/fake/",
        views.FakePaymentView.as_view(),
        name="payment_fake",
    ),
    path(
        "payment/<uuid:payment_id>/transfer/",
        views.TransferPaymentView.as_view(),
        name="payment_transfer",
    ),
    path(
        "payment/<uuid:payment_id>/payu/",
        views.PayUPaymentView.as_view(),
        name="payment_payu",
    ),
    path(
        "payment/payu/<str:contest_slug>/",
        views.PayUPaymentRedirectView.as_view(),
        name="payment_payu_redirect",
    ),
    path(
        "payment/payu/notification/<uuid:payment_id>/",
        views.PayUNotificationView.as_view(),
        name="payment_payu_notification",
    ),
    path(
        "payment/<uuid:payment_id>/paypal/",
        views.PayPalDispatchView.as_view(),
        name="payment_paypal",
    ),
    path(
        "payment/paypal/success/<uuid:payment_id>/",
        views.PayPalSuccessRedirectView.as_view(),
        name="payment_paypal_success",
    ),
    path(
        "payment/paypal/failure/<uuid:payment_id>/",
        views.PayPalFailureRedirectView.as_view(),
        name="payment_paypal_failure",
    ),
    path(
        "<str:slug>/print/", views.AddPackageForPrinting.as_view(), name="labels_start"
    ),
    path(
        "print/<uuid:package_id>/",
        views.LabelPrintoutView.as_view(),
        name="labels_print",
    ),
    path(
        "<str:slug>/mgmt/delivery/",
        views.AddPackageOfDelivered.as_view(),
        name="delivery_select",
    ),
    path(
        "mgmt/delivery/<uuid:pk>/",
        views.ProcessPackageDelivered.as_view(),
        name="delivery_process",
    ),
    path(
        "<str:slug>/mgmt/payments/",
        views.PaymentManagementView.as_view(),
        name="payment_list",
    ),
    path(
        "mgmt/payments/<uuid:pk>/",
        views.PaymentReceivedView.as_view(),
        name="payment_process",
    ),
    path("<str:slug>/judging/", views.JudgingListView.as_view(), name="judging_list"),
    path(
        "<str:slug>/judging-finals/",
        views.JudgingFinalsListView.as_view(),
        name="judging_finals_list",
    ),
    path(
        "<str:slug>/judging-bos/",
        views.JudgeBosView.as_view(),
        name="judging_bos_view",
    ),
    path(
        "<slug:slug>/judging-bos/edit/",
        views.JudgeBosSelect.as_view(),
        name="judging_bos_select",
    ),
    path(
        "<str:slug>/judging-finals/<uuid:category_id>",
        views.JudgingFinalsCategoryView.as_view(),
        name="judging_finals_category",
    ),
    path(
        "scoresheet/<uuid:pk>/", views.ScoreSheetView.as_view(), name="scoresheet_view"
    ),
    path(
        "scoresheet/<uuid:pk>/edit/",
        views.ScoreSheetEdit.as_view(),
        name="scoresheet_edit",
    ),
    path(
        "entry/<uuid:entry>/scoresheet/",
        views.ScoreSheetCreate.as_view(),
        name="scoresheet_create",
    ),
    path(
        "<str:contest_slug>/results/",
        views.MedalsListView.as_view(),
        name="contest_results",
    ),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    path("partners/", views.PartnersGalleryView.as_view(), name="partners_gallery"),
]

tacom/tacom/urls.py
from allauth.account import views as allauth_views
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = i18n_patterns(
    path(
        'accounts/password/change/',
        login_required(
            allauth_views.PasswordChangeView.as_view(
                success_url=reverse_lazy('contest:profile')
            )
        ),
        name='account_change_password'
    ),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('contest/', include('contest.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('tinymce/', include('tinymce.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', RedirectView.as_view(url='/contest'), name='home'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

tacom/contest/models/user.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField


# from contest.managers import UserManager


def validate_gdpr_consent(value):
    if not value:
        raise ValidationError("You must accept Privacy Policy to create an account.")


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_("Email must be set"))

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)

    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    country = CountryField(verbose_name=_("Country"), blank=True)
    phone = models.CharField(_("Phone number"), max_length=15, blank=True)
    address = models.CharField(_("Address"), max_length=200, blank=True)

    class JudgingLanguage(models.TextChoices):
        polish = "pl", _("Polish")
        english = "en", _("English")

    language = models.CharField(
        _("I would like to get feedback on my meads in"),
        choices=JudgingLanguage.choices,
        blank=True,
        max_length=2,
    )

    gdpr_consent = models.BooleanField(
        default=False,
        validators=[validate_gdpr_consent],
        verbose_name=_("Privacy Policy accepted"),
    )
    gdpr_consent_date = models.DateTimeField(auto_now_add=True)

    rebate_code_text = models.CharField(
        _("Rebate code"),
        max_length=15,
        blank=True,
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        db_table = "auth_user"

    def __str__(self):
        if self.last_name and self.first_name:
            return f"{self.last_name} {self.first_name}"
        return self.email

    @cached_property
    def profile_complete(self):
        return (
            self.first_name
            and self.last_name
            and self.country
            and self.phone
            and self.address
            and self.language
        )

    @cached_property
    def contest(self):
        # temp solution for one-competition site
        from contest.models import Contest

        return Contest.objects.first().slug


class Participant(User):
    class Meta:
        proxy = True
        verbose_name = _("Participant")
        verbose_name_plural = _("Participants")

    @property
    def entries_stats(self, contest=None):
        entries_qs = self.entries.all()
        if contest:
            entries_qs = entries_qs.filter(category__contest=contest)

        entries = (
            entries_qs.values("is_paid", "is_received")
            # .annotate(paid=models.Count('is_paid'), received=models.Count('is_received'))
            .annotate(count=models.Count("is_paid"))
        )
        return {
            "total": entries.aggregate(total=models.Sum("count")).get("total") or 0,
            "paid": entries.filter(is_paid=True).count(),
            "received": entries.filter(is_received=True).count(),
        }

    @property
    def entries_total(self):
        return self.entries_stats.get("total")

    entries_total.fget.short_description = _("Registered")

    @property
    def entries_paid(self):
        return self.entries_stats.get("paid")

    entries_paid.fget.short_description = _("Paid")

    @property
    def entries_received(self):
        return self.entries_stats.get("received")

    entries_received.fget.short_description = _("Received")

tacom/contest/views/contest.py
from contest.models import Category, Contest
from django.db.models import Prefetch
from django.shortcuts import get_object_or_404
from django.utils.functional import cached_property
from django.views.generic import DetailView
from django.views.generic.base import ContextMixin


class ContestDetailView(DetailView):
    model = Contest
    # queryset = Contest.objects.prefetch_related('categories__style')  # 2 queries
    # queryset = Contest.published.prefetch_related(
    #     #     Prefetch("categories", queryset=Category.objects.select_related("style"))
    #     # )  # 1 query

    # why i have to use get_queryset here becayse adding .prefeech_related executes immediatelly

    def get_queryset(self):
        return Contest.published.prefetch_related(
            Prefetch("categories", queryset=Category.objects.select_related("style"))
        )

    def get_template_names(self):
        """
        based on  htmx header: HX-Request, if "embed" == "true",
        the template used will be only view-specific data,
        otherwise it will extend base.html, to add bars, styling, etc

        """
        if self.request.headers.get("HX-Request") == "true":
            return ["contest/contest/contest_detail.html"]
        else:
            return ["contest/contest/contest_detail_standalone.html"]


class ContestRulesView(DetailView):
    model = Contest
    template_name = "contest/contest/contest_rules.html"


class ContestDeliveryAddressView(DetailView):
    model = Contest
    template_name = "contest/contest/contest_delivery_addr.html"
    queryset = Contest.published


class ContestContextMixin(ContextMixin):
    contest_slug_kwarg = "slug"
    kwargs: dict

    @cached_property
    def contest(self) -> Contest:
        slug = self.kwargs.get(self.contest_slug_kwarg)
        return get_object_or_404(Contest, slug=slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contest"] = self.contest
        return context

tacom/contest/templates/contest/add_entry.html
{% extends 'contest/base.html' %}
{% block content %}
{% load i18n %}


<h1>{{ contest.title }}</h1>
{%  include 'contest/entries.html' %}

<h2>{{ style.name }}</h2>
<h3>{% translate "Provide entry details:" %}</h3>
<form method="post" action="">
  {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>

    {%  if error %}
        <a href="{% url 'contest:add_entry_contest' contest.slug %}" class="btn btn-outline-secondary">
            {% translate "Go back" %}
        </a>
    {%  endif %}
  <button type="submit" class="btn btn-primary">
      {% translate "Save" %}
  </button>
  <a class="btn btn-secondary" href="
        {% if form.return_url %}
            {{ form.return_url }}
        {% else %}
{#            {{ request.META.HTTP_REFERER }}#}
            javascript:window.history.back()
        {% endif %}">
      {% translate "Cancel" %}
  </a>
</form>

{% endblock content %}

tacom/contest/templates/contest/add_entry_style_list.html
{% extends 'contest/base.html' %}
{% block content %}
{% load i18n %}
{% load bootstrap_icons %}

{%  include 'contest/entries.html' %}
<br />
<a class="btn btn-outline-primary" href="{% url 'contest:payment_start' contest.slug %}">
    {% bs_icon 'cash-coin' size='1.5em' %}
    {% translate 'Pay for entries' %}
</a>

<a class="btn btn-outline-primary" href="{% url 'contest:labels_start' contest.slug %}">
    {% bs_icon 'file-richtext' size='1.5em' %}
    {% translate 'Print bottle labels' %}
</a>

<a
    class="btn btn-outline-primary"
    href="{% url 'contest:contest_address' contest.slug %}"
    target="_blank"
>
    {% bs_icon 'truck' size='1.5em' %}
    {% translate 'Print delivery address' %}
</a>

<br /><br />
{% if can_add %}
    <h3 class="h3">{% translate "Select style in which you would like to register an entry" %}</h3>
{#    Display info about remaining global limit #}
    {% if contest_limit_left %}
        <h4 class="h4">
            {% translate "Number of slots left in the contest" %}: {{ contest_limit_left }}
            <span
                data-toggle="tooltip"
                title="{%  translate "You will be able to register and pay for your entries as long as there is at least one slot left." %}"
            >
                {% bs_icon 'info-circle-fill' size='0.8em'%}
            </span>
        </h4>
    {% endif %}
{#    Display info about remaining participant limit #}
    {% if user_limit_left %}
        <h4 class="h4">
            {% translate "Number of slots left towards participant limit" %}: {{ user_limit_left }}
            <span
                data-toggle="tooltip"
                title="{{ contest.entry_user_limit }} {% translate "is the maximum number of entries per participant in this competition" %}"
            >
                {% bs_icon 'info-circle-fill' size='0.8em'%}
            </span>
        </h4>
        <br/><br/>
    {% endif %}
        <table class="table">
            {% for category in categories %}
                {% if forloop.counter == 1 %}

                <tr>
                    <th>{% translate 'Style' %}</th>
                    <th>{% translate 'Maximum entries per brewer' %}</th>
                    <th>{% translate 'Style description' %}</th>
                </tr>
                {% endif %}
                <tr><td>

                    <a class="btn btn-outline-primary" href = "{% url 'contest:add_entry_category' category.id %}">
                        {{ category.style.name }}
                    </a>
                </td><td>
                    {{ category.entries_limit }}
                </td><td>
                    <a href = "{% url 'contest:style_detail' category.style.slug %}">
                        {%  translate "style details" %}
                    </a>
                </td></tr>


            {% empty %}
                {% translate "You cannot add entries for this contest" %}

            {% endfor %}
        </table>
{% else %}
    <h3 class="h3">{% translate "You cannot register entries anymore."%} </h3>
    <h4 class="h4">{{ limit_exhausted_info }}</h4>

{% endif %}


{% endblock content %}

tacom/contest/templates/contest/entry_confirm_delete.html
{% extends "contest/base.html" %}

{% block content %}
{%  load i18n %}
<form method="post" action="">
  {% csrf_token %}
    <h3>{% translate "Are you sure you want to delete following entry?" %}</h3>
    <h4>{% translate 'Style' %}: <small>{{ entry.category.style }}</small></h4>
    <h4>{% translate 'Name' %}: <small>{{ entry.name }}</small></h4>

    {{ form }}
    <a class="btn btn-primary" href="{{ view.get_success_url }}">Cancel</a>
    <button type="submit" class="btn btn-danger">
      {% translate "Delete" %}
  </button>
</form>

{% endblock %}

tacom/contest/templates/contest/header.html
<div class="container p-5 text-bg-primary text-center rounded-top shadow">
    <h1>TAsting COMpetitions</h1>
</div>

tacom/contest/templates/contest/judging_list_by_style.html
{% extends "contest/base.html" %}

{% block content %}
{% load i18n %}
{% load static %}
{% load bootstrap_icons %}
{% load user_flag %}
    {% regroup entries by category.style as entries_by_style %}
    {% for style in entries_by_style %}
        <p class="display-6">{{ style.grouper }}</p>
        <table class="table">
        <tr>
            <th class="col-1"></th>
            <th class="col-1">{% translate 'Code' %}</th>
            <th class="col-1">{% translate 'Language' %}</th>
            <th class="col-1"></th>
            <th>{% translate 'Actions' %}</th>
        </tr>
        {% for entry in style.list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    {{ entry.code }}</td>
                <td>
                    <img src="{% static ""%}{% flag entry.brewer %}" alt="Judging language flag"/>
                </td>
                <td>
{#                    {{ entry.medal }}#}
                </td>
                <td>
                    <a
                        class="btn btn-outline-primary {% if not entry.scoresheet %}disabled{% endif %}"
                        {% if entry.scoresheet %}
                            href="{% url 'contest:scoresheet_view' entry.scoresheet.id %}"
                        {% endif %}
                        title="{% translate 'View score sheet' %}"
                        data-toggle="tooltip"
                    >
                        {% bs_icon 'eye' size='1.5em' %}
                    </a>

                    {% if entry.scoresheet %}
                        <a class="btn btn-outline-primary"
                           href="{% url 'contest:scoresheet_edit' entry.scoresheet.id %}"
                           title="{% translate 'Edit score sheet' %}"
                           data-toggle="tooltip"
                       >
                    {% else %}
                        <a class="btn btn-primary"
                           href="{% url 'contest:scoresheet_create' entry.id %}"
                           title="{% translate 'Create score sheet' %}"
                           data-toggle="tooltip"
                       >
                    {% endif %}
                        {% bs_icon 'pencil' size='1.5em' %}
                    </a>

                </td>
            </tr>
        {% endfor %}
        </table>
    {%  endfor %}

{% endblock %}

tacom/contest/templates/contest/profile.html
{% extends 'contest/base.html' %}
{% block content %}
{% load bootstrap_icons %}
{% load i18n %}
<div class="container border rounded-3 p-3">
    <h2>{% translate 'My User Profile' %}</h2>
    <table>
        <tr>
            <td>{% translate "Country" %}:</td>
            <td> {% if user.country %}
                    <img src="{{ user.country.flag }}" alt="User country flag"/>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>{% translate "First name" %}:</td>
            <td> {{ user.first_name }}</td>
        </tr>
        <tr>
            <td>{% translate "Last name" %}:</td>
            <td> {{ user.last_name }}</td>
        </tr>
        <tr>
            <td>{% translate "Primary email" %}:</td>
            <td> {{ user.email }}</td>
        </tr>
        <tr>
            <td>{% translate "Phone number" %}:</td>
            <td> {{ user.phone }}</td>
        </tr>
        <tr>
            <td>{% translate "Address" %}:</td>
            <td> {{ user.address | linebreaks }}</td>
        </tr>
        <tr>
            <td>{% translate "Preferred judging language" %}:</td>
            <td> {{ user.get_language_display }}</td>
        </tr>
        <tr>
            <td>{% translate "Rebate code" %}:</td>
            <td>
                {% if user.rebate_code_text %}
                {% bs_icon 'check' size='1.5em' %}
                {% else %}
                {% bs_icon 'x' size='1.5em' %}
                {% endif %}
            </td>
        </tr>
    </table>
    <br />
    <div>
    <a class="btn btn-primary" href="{% url 'account_change_password' %}">{% translate "change password" %}</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">{% translate "edit email" %}</a>
    <a class="btn btn-primary" href="{% url 'contest:profile_edit' %}">{% translate "edit profile data" %}</a>
{#    {% include 'contest/entries.html' %}#}
    <a class="btn btn-primary"
       href="{% url 'contest:add_entry' %}">
        {% translate "entries" %}
    </a></div>
</div>
<br/>
<div class="container border rounded-3 p-3">
    <h2 class="m-2">{% translate 'Your judge certification information' %}: </h2>
    {% include 'contest/judges/judge_certification.html' %}
    </div>

{% endblock content %}

tacom/contest/templates/contest/scoresheet_entry.html
{% load i18n %}
{% load static %}
{% load user_flag %}

<dl class="row">
    <dt class="col-sm-1">{% translate 'Style' %}:</dt>
    <dd class="col-sm-5">{{ scoresheet.entry.category.style.name }}</dd>

    <dt class="col-sm-1">{% translate 'ABV' %}:</dt>
    <dd class="col-sm-5">{{ scoresheet.entry.alcohol_content }}</dd>

    <dt class="col-sm-1">{% translate 'Entry' %}:</dt>
    <dd class="col-sm-5">{{ scoresheet.entry.code }}
        {% url 'contest:scoresheet_view' scoresheet.id as display_url%}
        </dd>

    <dt class="col-sm-1">{% translate 'Sweetness' %}:</dt>
    <dd class="col-sm-5">{{ scoresheet.entry.get_sweetness_display }}</dd>

    <dt class="col-sm-1">{% translate 'Language' %}:</dt>
    <dd class="col-sm-5">
        {{ scoresheet.entry.brewer.get_language_display }}
        <img src="{% static ""%}{% flag scoresheet.entry.brewer %}" alt="Judging language flag"/>
    </dd>

    <dt class="col-sm-1">{% translate 'Carbonation' %}:</dt>
    <dd class="col-sm-5">{{ scoresheet.entry.get_carbonation_display }}</dd>
</dl>
<p>
<a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseDescription" role="button">
    {% translate 'Entry description' %}
</a>
</p>
<p>
<div class="collapse" id="collapseDescription">
  <div class="card card-body">
    {{ scoresheet.entry.extra_info|linebreaks }}
  </div>
</div>
</p>

tacom/contest/templates/contest/style_detail.html
{% extends 'contest/base.html' %}
{% block content %}

    <h1> {{ style.name }}</h1>
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
    {% if LANGUAGE_CODE == 'pl' %}
        {{ style.description_pl | safe }}
    {% else %}
        {{ style.description | safe }}
    {% endif %}

{% endblock content %}