tacom/contest/urls.py
from django.urls import path
from django.views.generic import DetailView

from . import views
from .models import Style

app_name = "contest"

urlpatterns = [
    path("", views.PublishedContestListView.as_view(), name="contest_list"),
    path(
        "details/<str:slug>/", views.ContestDetailView.as_view(), name="contest_detail"
    ),
    path(
        "details/<str:slug>/rules/",
        views.ContestRulesView.as_view(),
        name="contest_rules",
    ),
    path(
        "details/<str:slug>/addr/",
        views.ContestDeliveryAddressView.as_view(),
        name="contest_address",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/edit/", views.ProfileEditView.as_view(), name="profile_edit"),
    path("style/<str:slug>/", DetailView.as_view(model=Style), name="style_detail"),
    path("entry/add/", views.AddEntryContestListView.as_view(), name="add_entry"),
    path(
        "entry/add/contest/<str:slug>/",
        views.AddEntryStyleListView.as_view(),
        name="add_entry_contest",
    ),
    path(
        "entry/contest/<str:slug>/",
        views.UsersEntryListView.as_view(),
        name="user_entry_list",
    ),
    path(
        "entry/add/category/<uuid:pk>/",
        views.AddEntryView.as_view(),
        name="add_entry_category",
    ),
    path("entry/edit/<uuid:pk>/", views.EditEntryView.as_view(), name="entry_edit"),
    path(
        "entry/delete/<uuid:pk>/", views.DeleteEntryView.as_view(), name="entry_delete"
    ),
    path(
        "entry/results/<uuid:pk>/",
        views.MyScoreSheetView.as_view(),
        name="entry_results",
    ),
    path(
        "<str:slug>/payment/",
        views.AddPackageForPayment.as_view(),
        name="payment_start",
    ),
    path(
        "<str:slug>/payment/<uuid:package_id>/",
        views.SelectPaymentMethodView.as_view(),
        name="payment_method_selection",
    ),
    path(
        "payment/<uuid:payment_id>/fake/",
        views.FakePaymentView.as_view(),
        name="payment_fake",
    ),
    path(
        "payment/<uuid:payment_id>/transfer/",
        views.TransferPaymentView.as_view(),
        name="payment_transfer",
    ),
    path(
        "payment/<uuid:payment_id>/payu/",
        views.PayUPaymentView.as_view(),
        name="payment_payu",
    ),
    path(
        "payment/payu/<str:contest_slug>/",
        views.PayUPaymentRedirectView.as_view(),
        name="payment_payu_redirect",
    ),
    path(
        "payment/payu/notification/<uuid:payment_id>/",
        views.PayUNotificationView.as_view(),
        name="payment_payu_notification",
    ),
    path(
        "payment/<uuid:payment_id>/paypal/",
        views.PayPalDispatchView.as_view(),
        name="payment_paypal",
    ),
    path(
        "payment/paypal/success/<uuid:payment_id>/",
        views.PayPalSuccessRedirectView.as_view(),
        name="payment_paypal_success",
    ),
    path(
        "payment/paypal/failure/<uuid:payment_id>/",
        views.PayPalFailureRedirectView.as_view(),
        name="payment_paypal_failure",
    ),
    path(
        "<str:slug>/print/", views.AddPackageForPrinting.as_view(), name="labels_start"
    ),
    path(
        "print/<uuid:package_id>/",
        views.LabelPrintoutView.as_view(),
        name="labels_print",
    ),
    path(
        "<str:slug>/mgmt/delivery/",
        views.AddPackageOfDelivered.as_view(),
        name="delivery_select",
    ),
    path(
        "mgmt/delivery/<uuid:pk>/",
        views.ProcessPackageDelivered.as_view(),
        name="delivery_process",
    ),
    path(
        "<str:slug>/mgmt/payments/",
        views.PaymentManagementView.as_view(),
        name="payment_list",
    ),
    path(
        "mgmt/payments/<uuid:pk>/",
        views.PaymentReceivedView.as_view(),
        name="payment_process",
    ),
    path("<str:slug>/judging/", views.JudgingListView.as_view(), name="judging_list"),
    path(
        "<str:slug>/judging-finals/",
        views.JudgingFinalsListView.as_view(),
        name="judging_finals_list",
    ),
    path(
        "<str:slug>/judging-bos/",
        views.JudgeBosView.as_view(),
        name="judging_bos_view",
    ),
    path(
        "<slug:slug>/judging-bos/edit/",
        views.JudgeBosSelect.as_view(),
        name="judging_bos_select",
    ),
    path(
        "<str:slug>/judging-finals/<uuid:category_id>",
        views.JudgingFinalsCategoryView.as_view(),
        name="judging_finals_category",
    ),
    path(
        "scoresheet/<uuid:pk>/", views.ScoreSheetView.as_view(), name="scoresheet_view"
    ),
    path(
        "scoresheet/<uuid:pk>/edit/",
        views.ScoreSheetEdit.as_view(),
        name="scoresheet_edit",
    ),
    path(
        "entry/<uuid:entry>/scoresheet/",
        views.ScoreSheetCreate.as_view(),
        name="scoresheet_create",
    ),
    path(
        "<str:contest_slug>/results/",
        views.MedalsListView.as_view(),
        name="contest_results",
    ),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    path("partners/", views.PartnersGalleryView.as_view(), name="partners_gallery"),
]

tacom/contest/urls/urls.py
from contest import views
from contest.models import Style
from django.urls import path
from django.views.generic import DetailView

urlpatterns = [
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/edit/", views.ProfileEditView.as_view(), name="profile_edit"),
    path("style/<str:slug>/", DetailView.as_view(model=Style), name="style_detail"),
    path("entry/add/", views.AddEntryContestListView.as_view(), name="add_entry"),
    path(
        "entry/add/contest/<str:slug>/",
        views.AddEntryStyleListView.as_view(),
        name="add_entry_contest",
    ),
    path(
        "entry/contest/<str:slug>/",
        views.UsersEntryListView.as_view(),
        name="user_entry_list",
    ),
    path(
        "entry/add/category/<uuid:pk>/",
        views.AddEntryView.as_view(),
        name="add_entry_category",
    ),
    path("entry/edit/<uuid:pk>/", views.EditEntryView.as_view(), name="entry_edit"),
    path(
        "entry/delete/<uuid:pk>/", views.DeleteEntryView.as_view(), name="entry_delete"
    ),
    path(
        "entry/results/<uuid:pk>/",
        views.MyScoreSheetView.as_view(),
        name="entry_results",
    ),
    path(
        "<str:slug>/payment/",
        views.AddPackageForPayment.as_view(),
        name="payment_start",
    ),
    path(
        "<str:slug>/payment/<uuid:package_id>/",
        views.SelectPaymentMethodView.as_view(),
        name="payment_method_selection",
    ),
    path(
        "payment/<uuid:payment_id>/fake/",
        views.FakePaymentView.as_view(),
        name="payment_fake",
    ),
    path(
        "payment/<uuid:payment_id>/transfer/",
        views.TransferPaymentView.as_view(),
        name="payment_transfer",
    ),
    path(
        "payment/<uuid:payment_id>/payu/",
        views.PayUPaymentView.as_view(),
        name="payment_payu",
    ),
    path(
        "payment/payu/<str:contest_slug>/",
        views.PayUPaymentRedirectView.as_view(),
        name="payment_payu_redirect",
    ),
    path(
        "payment/payu/notification/<uuid:payment_id>/",
        views.PayUNotificationView.as_view(),
        name="payment_payu_notification",
    ),
    path(
        "payment/<uuid:payment_id>/paypal/",
        views.PayPalDispatchView.as_view(),
        name="payment_paypal",
    ),
    path(
        "payment/paypal/success/<uuid:payment_id>/",
        views.PayPalSuccessRedirectView.as_view(),
        name="payment_paypal_success",
    ),
    path(
        "payment/paypal/failure/<uuid:payment_id>/",
        views.PayPalFailureRedirectView.as_view(),
        name="payment_paypal_failure",
    ),
    path(
        "<str:slug>/print/", views.AddPackageForPrinting.as_view(), name="labels_start"
    ),
    path(
        "print/<uuid:package_id>/",
        views.LabelPrintoutView.as_view(),
        name="labels_print",
    ),
    path(
        "<str:slug>/mgmt/delivery/",
        views.AddPackageOfDelivered.as_view(),
        name="delivery_select",
    ),
    path(
        "mgmt/delivery/<uuid:pk>/",
        views.ProcessPackageDelivered.as_view(),
        name="delivery_process",
    ),
    path(
        "<str:slug>/mgmt/payments/",
        views.PaymentManagementView.as_view(),
        name="payment_list",
    ),
    path(
        "mgmt/payments/<uuid:pk>/",
        views.PaymentReceivedView.as_view(),
        name="payment_process",
    ),
    path("<str:slug>/judging/", views.JudgingListView.as_view(), name="judging_list"),
    path(
        "<str:slug>/judging-finals/",
        views.JudgingFinalsListView.as_view(),
        name="judging_finals_list",
    ),
    path(
        "<str:slug>/judging-bos/",
        views.JudgeBosView.as_view(),
        name="judging_bos_view",
    ),
    path(
        "<slug:slug>/judging-bos/edit/",
        views.JudgeBosSelect.as_view(),
        name="judging_bos_select",
    ),
    path(
        "<str:slug>/judging-finals/<uuid:category_id>",
        views.JudgingFinalsCategoryView.as_view(),
        name="judging_finals_category",
    ),
    path(
        "scoresheet/<uuid:pk>/", views.ScoreSheetView.as_view(), name="scoresheet_view"
    ),
    path(
        "scoresheet/<uuid:pk>/edit/",
        views.ScoreSheetEdit.as_view(),
        name="scoresheet_edit",
    ),
    path(
        "entry/<uuid:entry>/scoresheet/",
        views.ScoreSheetCreate.as_view(),
        name="scoresheet_create",
    ),
    path(
        "<str:contest_slug>/results/",
        views.MedalsListView.as_view(),
        name="contest_results",
    ),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    path("partners/", views.PartnersGalleryView.as_view(), name="partners_gallery"),
]

tacom/tacom/urls.py
from allauth.account import views as allauth_views
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = i18n_patterns(
    path(
        'accounts/password/change/',
        login_required(
            allauth_views.PasswordChangeView.as_view(
                success_url=reverse_lazy('contest:profile')
            )
        ),
        name='account_change_password'
    ),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('contest/', include('contest.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('tinymce/', include('tinymce.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', RedirectView.as_view(url='/contest'), name='home'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

tacom/contest/models/judges.py
from contest.models import Contest, User
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _


class JudgeCertification(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_mead_bjcp = models.BooleanField(default=False, verbose_name=_("BJCP Mead"))
    is_mjp = models.BooleanField(default=False, verbose_name=_("MJP"))
    is_other = models.BooleanField(default=False, verbose_name=_("Other"))
    mjp_level = models.IntegerField(
        blank=True,
        null=True,
        verbose_name=_("MJP level"),
        validators=[MinValueValidator(1), MaxValueValidator(5)],
    )
    other_description = models.TextField(blank=True, verbose_name=_("Description"))

    def clean(self):
        super().clean()

        # At least one certification must be selected
        # This was moved to save() as no certification (via dedicated view)
        # implies deletion of certification

        # if not (self.is_mead_bjcp or self.is_mjp or self.is_other):
        #     raise ValidationError(
        #         _("At least one certification type must be selected.")
        #     )

        # If MJP is selected, mjp_level must be provided
        if self.is_mjp and self.mjp_level is None:
            raise ValidationError(
                {
                    "mjp_level": _(
                        "MJP level is required when MJP certification is selected."
                    )
                }
            )

        # If Other is selected, other_description cannot be blank
        if self.is_other and not self.other_description.strip():
            raise ValidationError(
                {
                    "other_description": _(
                        "Description is required when Other certification is selected."
                    )
                }
            )
        # Clean extra fields if checkbox is unchecked
        if not self.is_mjp:
            self.mjp_level = None
        if not self.is_other:
            self.other_description = ""

    def save(self, *args, **kwargs):
        if not (self.is_mead_bjcp or self.is_mjp or self.is_other):
            raise ValueError("At least one certification type must be selected.")
        super().save(*args, **kwargs)


class JudgeInCompetition(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)

    class Status(models.TextChoices):
        APPLICATION = "application", _("Application")
        APPROVED = "approved", _("Approved")
        REJECTED = "rejected", _("Rejected")

    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.APPLICATION
    )

    # approved = "ApprovedJudgeManager"

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "contest"],
                name="unique_judge_application_per_contest",
            )
        ]
        verbose_name = _("Judge")
        verbose_name_plural = _("Judges")


class ApprovedJudgeManager(models.Manager):
    def get_queryset(self):
        return JudgeInCompetition.objects.filter(
            status=JudgeInCompetition.Status.APPROVED
        )


JudgeInCompetition.approved = ApprovedJudgeManager()

tacom/contest/views/contest.py
from contest.models import Category, Contest
from django.db.models import Prefetch
from django.shortcuts import get_object_or_404
from django.utils.functional import cached_property
from django.views.generic import DetailView
from django.views.generic.base import ContextMixin


class ContestDetailView(DetailView):
    model = Contest
    # queryset = Contest.objects.prefetch_related('categories__style')  # 2 queries
    # queryset = Contest.published.prefetch_related(
    #     #     Prefetch("categories", queryset=Category.objects.select_related("style"))
    #     # )  # 1 query

    # why i have to use get_queryset here becayse adding .prefeech_related executes immediatelly

    def get_queryset(self):
        return Contest.published.prefetch_related(
            Prefetch("categories", queryset=Category.objects.select_related("style"))
        )

    def get_template_names(self):
        """
        based on  htmx header: HX-Request, if "embed" == "true",
        the template used will be only view-specific data,
        otherwise it will extend base.html, to add bars, styling, etc

        """
        if self.request.headers.get("HX-Request") == "true":
            return ["contest/contest/contest_detail.html"]
        else:
            return ["contest/contest/contest_detail_standalone.html"]


class ContestRulesView(DetailView):
    model = Contest
    template_name = "contest/contest/contest_rules.html"


class ContestDeliveryAddressView(DetailView):
    model = Contest
    template_name = "contest/contest/contest_delivery_addr.html"
    queryset = Contest.published


class ContestContextMixin(ContextMixin):
    contest_slug_kwarg = "slug"
    kwargs: dict

    @cached_property
    def contest(self) -> Contest:
        slug = self.kwargs.get(self.contest_slug_kwarg)
        return get_object_or_404(Contest, slug=slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contest"] = self.contest
        return context

tacom/contest/views/general.py
from contest.models import Contest
from django.shortcuts import redirect
from django.views.generic import ListView


class PublishedContestListView(ListView):
    ordering = ["-judging_date_from"]
    queryset = Contest.published
    template_name = "contest/general/contest_list.html"

    def get(self, *args, **kwargs):
        if self.queryset.count() == 1:
            return redirect("contest:contest_detail", slug=self.queryset.first().slug)
        return super().get(*args, **kwargs)

tacom/contest/templates/contest/judges/judge_application.html
{% extends 'contest/base.html' %}
{% load i18n %}
{% block content %}
<h2 class="m-2">{% translate 'Your judge certification information' %}: </h2>
{% include 'contest/judges/judge_certification.html' %}

<h2 class="m-2">{% translate 'Apply for judging' %}</h2>
<div hx-get="{% url 'contest:judge_application_widget' contest.slug %}" hx-trigger="load"
     id="judge_application_widget"></div>

{% endblock %}

tacom/contest/templates/contest/judges/judge_certification.html
<div class="container border rounded d-md-inline-block p-3">
    <div id="certification" hx-get="{% url 'contest:judge_certification_read' %}" hx-trigger="load" hx-swap="outerHTML"></div>
</div>
    <script>
        function initJudgeCertificationForm(container) {
            const isMjp = container.querySelector("#id_is_mjp");
            const isOther = container.querySelector("#id_is_other");
            const mjpWrapper = container.querySelector("#mjp-level-wrapper");
            const otherWrapper = container.querySelector("#other-description-wrapper");

            if (!isMjp || !isOther || !mjpWrapper || !otherWrapper) return;

            function toggleFields() {
                // ALWAYS read the actual current checkbox state
                mjpWrapper.style.display = isMjp.checked ? "block" : "none";
                otherWrapper.style.display = isOther.checked ? "block" : "none";
            }

            // Remove previous listeners
            isMjp.onchange = null;
            isOther.onchange = null;

            // Attach listeners
            isMjp.addEventListener("change", toggleFields);
            isOther.addEventListener("change", toggleFields);

            // Initialize visibility once after listeners are attached
            toggleFields();
        }

        // Initial load
        document.addEventListener("DOMContentLoaded", function () {
            const container = document.querySelector("#certification");
            if (container) initJudgeCertificationForm(container);
        });

        // HTMX swap: use afterSettle to ensure DOM is ready
        document.body.addEventListener("htmx:afterSettle", function (event) {
            const container = document.querySelector("#certification");
            if (container) initJudgeCertificationForm(container);
        });
    </script>

tacom/contest/templates/contest/judges/judge_certification_edit.html
{% load i18n %}
<div id="certification">
    <form hx-post="{% url 'contest:judge_certification_edit' %}" hx-target="#certification" hx-swap="outerHTML">
        {% csrf_token %}
        <table valign="top">
            <tr>
                <td class="align-top pe-3">
                    {{ form.is_mjp.label_tag }}
                </td>
                <td>
                    {{ form.is_mjp }}
                    <div id="mjp-level-wrapper">
                        {{ form.mjp_level.label_tag }}
                        {{ form.mjp_level }}
                        {% include 'contest/widgets/error.html' with form_errors=form.mjp_level.errors %}
                    </div>
                </td>
            </tr>


            <tr>
                <td class="align-top pe-3">
                    {{ form.is_mead_bjcp.label_tag }}
                </td>
                <td>
                    {{ form.is_mead_bjcp }}
                </td>
            </tr>

            <tr>
                <td class="align-top pe-3">
                    {{ form.is_other.label_tag }}
                </td>
                <td>
                    {{ form.is_other }}
                    <div id="other-description-wrapper">
                    {{ form.other_description.label_tag }}</br>
                    {{ form.other_description }}
                    {% include 'contest/widgets/error.html' with form_errors=form.other_description.errors %}
            </div>
                </td>
            </tr>


        </table>


        {% include 'contest/widgets/error.html' with form_errors=form.non_field_errors %}

        <button class="btn btn-primary" type="submit">{% translate "Save" %}</button>
        <button class="btn btn-secondary" hx-get="{% url 'contest:judge_certification_read' %}">{% translate "Cancel"%}
        </button>
    </form>
</div>

tacom/contest/templates/contest/judges/judge_certification_empty.html
{% load i18n %}
{% load bootstrap_icons %}
<div id="certification">
    <div><a class="btn btn-primary" hx-get="{% url 'contest:judge_certification_edit' %}" hx-target="#certification"
            hx-swap="outerHTML">{% bs_icon 'pencil-square' %}
    </a></div>
    <div>
        <p class="m-2 ">{% translate 'No judge certification information' %}</p>
    </div>
</div>

tacom/contest/templates/contest/judges/judge_certification_read.html
{% load i18n %}
{% load bootstrap_icons %}
<div id="certification">
     <div class="m-2"><a class="btn btn-secondary" hx-get="{% url 'contest:judge_certification_edit' %}" hx-target="#certification"
            hx-swap="outerHTML">{% bs_icon 'pencil-square' %}
    </a></div>
    <div class="m-2">
        <ul>
            {% if object.is_mjp %}
            <li>Mead Judging Programme, {% translate 'level' %} {{ object.mjp_level }} {% bs_icon 'check2'%}</li>
            {% endif %}
            {% if object.is_mead_bjcp %}
            <li>BJCP Mead  {% bs_icon 'check2'%}</li>
            {% endif %}
            {% if object.is_other %}
            <li>{% translate 'Other' %}: {{ object.other_description }}</li>
            {% endif %}
        </ul>
    </div>
<!--    <pre>-->
<!--    BJCP: {{ object.is_mead_bjcp }}-->
<!--    MJP: {{ object.is_mjp }}, {{ object.mjp_level }}-->
<!--    Other: {{ object.is_other }}, {{ object.other_description }}-->
<!--</pre>-->

</div>